#include "arm_codegen.h"
#include "arm_decode.h"

#include <charconv>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace {

struct Options {
    std::filesystem::path input;
    std::filesystem::path output;
    std::uint32_t image_base = 0x00100000;
    std::uint32_t start = 0x00100000;
    std::uint32_t size = 0x1000;
};

[[nodiscard]] auto parse_u32(std::string_view text) -> std::uint32_t {
    auto base = 10;
    if (text.starts_with("0x") || text.starts_with("0X")) {
        text.remove_prefix(2);
        base = 16;
    }
    std::uint32_t value{};
    const auto [end, error] = std::from_chars(text.data(), text.data() + text.size(), value, base);
    if (error != std::errc{} || end != text.data() + text.size()) {
        throw std::runtime_error{"invalid integer: " + std::string{text}};
    }
    return value;
}

[[nodiscard]] auto parse_options(int argc, char** argv) -> Options {
    Options options;
    for (auto index = 1; index < argc; ++index) {
        const std::string_view argument{argv[index]};
        const auto next = [&]() -> std::string_view {
            if (++index >= argc) throw std::runtime_error{"missing value after " + std::string{argument}};
            return argv[index];
        };
        if (argument == "--input") options.input = next();
        else if (argument == "--output") options.output = next();
        else if (argument == "--image-base") options.image_base = parse_u32(next());
        else if (argument == "--start") options.start = parse_u32(next());
        else if (argument == "--size") options.size = parse_u32(next());
        else throw std::runtime_error{"unknown argument: " + std::string{argument}};
    }
    if (options.input.empty() || options.output.empty()) {
        throw std::runtime_error{"--input and --output are required"};
    }
    if ((options.start | options.size) % 4 != 0 || options.start < options.image_base) {
        throw std::runtime_error{"ARM ranges must be aligned and lie inside the input image"};
    }
    return options;
}

[[nodiscard]] auto read_u32_le(std::span<const std::uint8_t> bytes, std::size_t offset)
    -> std::uint32_t {
    return static_cast<std::uint32_t>(bytes[offset]) |
           (static_cast<std::uint32_t>(bytes[offset + 1]) << 8) |
           (static_cast<std::uint32_t>(bytes[offset + 2]) << 16) |
           (static_cast<std::uint32_t>(bytes[offset + 3]) << 24);
}

auto emit(const Options& options) -> bool {
    std::ifstream input{options.input, std::ios::binary};
    if (!input) throw std::runtime_error{"unable to open input image"};
    const std::vector<std::uint8_t> bytes{
        std::istreambuf_iterator<char>{input}, std::istreambuf_iterator<char>{}};

    const auto offset = static_cast<std::size_t>(options.start - options.image_base);
    const auto end = offset + options.size;
    if (end > bytes.size()) throw std::runtime_error{"requested range exceeds input image"};

    std::filesystem::create_directories(options.output.parent_path());
    std::ofstream output{options.output};
    if (!output) throw std::runtime_error{"unable to create output file"};

    output << "// Generated by mk7-recompile. Do not edit or commit this file.\n"
              "#include <mk7/recomp/runtime.hpp>\n\n"
              "extern \"C\" void mk7_recomp_block_" << std::hex << options.start << "() {\n";

    armv4t::CodegenCtx context;
    context.current_function_addr = options.start;
    context.current_function_end_addr = options.start + options.size;

    auto supported = true;
    for (std::size_t cursor = offset; cursor < end; cursor += 4) {
        const auto address = options.image_base + static_cast<std::uint32_t>(cursor);
        const auto instruction = armv4t::ArmDecoder::decode(read_u32_le(bytes, cursor), address);
        auto unimplemented = false;
        output << armv4t::ArmCodegen::emit_instr(instruction, context, &unimplemented);
        if (unimplemented) {
            supported = false;
            std::cerr << "unsupported instruction at 0x" << std::hex << address << '\n';
        }
    }
    output << "}\n";
    return supported;
}

} // namespace

auto main(int argc, char** argv) -> int {
    try {
        const auto options = parse_options(argc, argv);
        return emit(options) ? 0 : 1;
    } catch (const std::exception& error) {
        std::cerr << "mk7-recompile: " << error.what() << '\n'
                  << "usage: mk7-recompile --input code.bin --output generated/block.cpp "
                     "[--image-base 0x100000] [--start 0x100000] [--size 0x1000]\n";
        return 2;
    }
}
