#include <mk7/recomp/runtime.hpp>
#include <algorithm>
#include <bit>
#include <cstring>
#include <cmath>
#include <iostream>
#include <vector>
ArmCpuState g_cpu{}; std::array<std::uint64_t,2> g_insn_count{}; bool g_insn_hook_armed=false;
namespace { std::span<std::byte> mem; std::vector<std::uint32_t> returns; bool unwind=false; std::uint32_t svc=~0u,dispatch=~0u,exclusive=~0u,input_buttons=0; float circle_x=0,circle_y=0; std::array<std::uint32_t,32> vfp_words{}; std::uint32_t fpscr{}; struct {std::uint32_t control{},tls{},ttbr0{},dacr{};} cp15;
const CtrGeneratedFunction* lookup(std::uint32_t target){auto a=target&~1u;const bool thumb=bool(target&1);for(std::size_t i=0;i<mk7_generated_function_count;++i)if(mk7_generated_functions[i].address==a&&mk7_generated_functions[i].thumb==thumb)return &mk7_generated_functions[i];const CtrGeneratedFunction* best=nullptr;for(std::size_t i=0;i<mk7_generated_function_count;++i){const auto& candidate=mk7_generated_functions[i];if(a>=candidate.address&&a<=candidate.end_address&&candidate.thumb==thumb&&(!best||candidate.end_address-candidate.address<best->end_address-best->address))best=&candidate;}return best;}
template<class T>T read(std::uint32_t a){T v{};if(std::uint64_t(a)+sizeof(T)<=mem.size())std::memcpy(&v,mem.data()+a,sizeof v);else unwind=true;return v;}
template<class T>void write(std::uint32_t a,T v){if(std::uint64_t(a)+sizeof(T)<=mem.size())std::memcpy(mem.data()+a,&v,sizeof v);else unwind=true;exclusive=~0u;}
}
void ctr_runtime_initialize(std::span<std::byte>m){mem=m;ctr_runtime_reset();} void ctr_runtime_reset(){g_cpu={};g_cpu.cpsr=0x10;g_insn_count={};returns.clear();unwind=false;svc=dispatch=exclusive=~0u;input_buttons=0;circle_x=circle_y=0;vfp_words={};fpscr=0;cp15={};}
std::uint32_t ctr_runtime_last_svc()noexcept{return svc;}std::uint32_t ctr_runtime_last_dispatch()noexcept{return dispatch;}RuntimeSnapshot ctr_runtime_snapshot()noexcept{return {g_cpu.R[15],dispatch,svc,input_buttons,circle_x,circle_y,g_insn_count[0],unwind};}void ctr_runtime_set_input(std::uint32_t b,float x,float y)noexcept{input_buttons=b;circle_x=x;circle_y=y;}bool runtime_should_yield()noexcept{return false;}bool runtime_unwinding()noexcept{return unwind;}void runtime_insn_slow()noexcept{}void runtime_tick(std::uint32_t)noexcept{}
void runtime_call_push_return(std::uint32_t a)noexcept{returns.push_back(a);}void runtime_call_cancel_return(std::uint32_t a)noexcept{if(!returns.empty()&&returns.back()==a)returns.pop_back();}bool runtime_call_should_return(std::uint32_t a)noexcept{if(!returns.empty()&&returns.back()==a){returns.pop_back();return true;}return false;}
void runtime_dispatch(std::uint32_t t)noexcept{dispatch=t;if(auto*f=lookup(t))f->function();else{unwind=true;std::cerr<<"[ctr] unknown branch 0x"<<std::hex<<t<<std::dec<<" (fail closed)\n";}}
void runtime_dispatch_with_exchange(std::uint32_t t)noexcept{g_cpu.cpsr=(t&1)?(g_cpu.cpsr|CPSR_T_BIT):(g_cpu.cpsr&~CPSR_T_BIT);runtime_dispatch(t);}
bool ctr_runtime_resume()noexcept{if(unwind)return false;const auto target=g_cpu.R[15]|((g_cpu.cpsr&CPSR_T_BIT)?1u:0u);svc=~0u;runtime_dispatch_with_exchange(target);return !unwind;}
void runtime_link_call(CtrLinkSlot*s)noexcept{runtime_dispatch_with_exchange(s->target);}void runtime_link_branch(CtrLinkSlot*s)noexcept{runtime_dispatch_with_exchange(s->target);}
void runtime_swi(std::uint32_t n)noexcept{svc=n;if(n==0x21u){static std::uint32_t next_handle=0x100u;g_cpu.R[0]=0;g_cpu.R[1]=next_handle++;}else g_cpu.R[0]=0xd8e007f7u;}void runtime_irq()noexcept{g_cpu.spsr[0]=g_cpu.cpsr;g_cpu.cpsr=(g_cpu.cpsr&~0x3fu)|0x92u;g_cpu.R[14]=g_cpu.R[15]+4;runtime_dispatch(0x18);}
void runtime_exception_return(std::uint32_t t)noexcept{g_cpu.cpsr=g_cpu.spsr[0];runtime_dispatch_with_exchange(t|((g_cpu.cpsr&CPSR_T_BIT)?1u:0u));}
void runtime_unimplemented_op(std::uint32_t pc,std::uint32_t raw)noexcept{unwind=true;std::cerr<<"[ctr] unsupported instruction "<<std::hex<<raw<<" at "<<pc<<std::dec<<"\n";}void runtime_unimplemented_op(const char* operation,std::uint32_t pc)noexcept{unwind=true;std::cerr<<"[ctr] unsupported "<<operation<<" at "<<std::hex<<pc<<std::dec<<"\n";}
std::uint32_t ctr_code_cycles(std::uint32_t)noexcept{return 1;}std::uint32_t ctr_refill_cycles(std::uint32_t)noexcept{return 3;}std::uint32_t ctr_cycle_combine(std::uint32_t a,std::uint32_t b,std::uint32_t c,bool d)noexcept{return a+b+c+unsigned(d);}
std::uint32_t runtime_code_cycles(std::uint32_t a,bool)noexcept{return ctr_code_cycles(a);}std::uint32_t runtime_mem_cycles(std::uint32_t,std::uint32_t,bool)noexcept{return 1;}std::uint32_t runtime_mul_cycles(std::uint32_t,bool,std::uint32_t e)noexcept{return 1+e;}
std::uint32_t runtime_coproc_read(std::uint8_t cp,std::uint8_t op1,std::uint8_t crn,std::uint8_t crm,std::uint8_t op2)noexcept{if((cp==10||cp==11)&&op1==7&&crn==1&&crm==0&&op2==0)return fpscr;if(cp!=15){unwind=true;return 0;}if(crn==1&&crm==0&&op1==0&&op2==0)return cp15.control;if(crn==13&&crm==0&&op1==0&&op2==3)return cp15.tls;if(crn==2)return cp15.ttbr0;if(crn==3)return cp15.dacr;return 0;}
void runtime_coproc_write(std::uint8_t cp,std::uint8_t op1,std::uint8_t crn,std::uint8_t crm,std::uint8_t op2,std::uint32_t v)noexcept{if((cp==10||cp==11)&&op1==7&&crn==1&&crm==0&&op2==0){fpscr=v;return;}if(cp!=15){unwind=true;return;}if(crn==1&&crm==0&&op1==0&&op2==0)cp15.control=v;else if(crn==13&&crm==0&&op1==0&&op2==3)cp15.tls=v;else if(crn==2)cp15.ttbr0=v;else if(crn==3)cp15.dacr=v;/* cache/TLB maintenance is coherent in the native map */}
void runtime_coproc_cdp(std::uint8_t cp,std::uint8_t,std::uint8_t,std::uint8_t,std::uint8_t,std::uint32_t w)noexcept{if(cp==15)return;if(cp!=10&&cp!=11){unwind=true;return;}const unsigned d=(((w>>12)&15u)*2u)+((w>>22)&1u),n=(((w>>16)&15u)*2u)+((w>>7)&1u),m=((w&15u)*2u)+((w>>5)&1u);if(d>=32||n>=32||m>=32){unwind=true;return;}const float fn=std::bit_cast<float>(vfp_words[n]),fm=std::bit_cast<float>(vfp_words[m]);float result{};if((w&0x0fb00e50u)==0x0e300a00u)result=fn+fm;else if((w&0x0fb00e50u)==0x0e300a40u)result=fn-fm;else if((w&0x0fb00e50u)==0x0e200a00u)result=fn*fm;else if((w&0x0fb00e50u)==0x0e800a00u)result=fn/fm;else if((w&0x0fbf0ed0u)==0x0eb00a40u)result=fm;else if((w&0x0fbf0ed0u)==0x0eb00ac0u)result=std::abs(fm);else if((w&0x0fbf0ed0u)==0x0eb10a40u)result=-fm;else if((w&0x0fbf0e50u)==0x0eb40a40u){fpscr&=0x0fffffffu;if(std::isnan(fn)||std::isnan(fm))fpscr|=0x30000000u;else if(fn==fm)fpscr|=0x60000000u;else if(fn<fm)fpscr|=0x80000000u;else fpscr|=0x20000000u;return;}else if((w&0x0fb80e50u)==0x0eb80a40u){result=float(std::bit_cast<std::int32_t>(vfp_words[m]));}else{unwind=true;return;}vfp_words[d]=std::bit_cast<std::uint32_t>(result);}
std::uint32_t runtime_vfp_word(unsigned i)noexcept{return i<vfp_words.size()?vfp_words[i]:0u;}void runtime_vfp_set_word(unsigned i,std::uint32_t v)noexcept{if(i<vfp_words.size())vfp_words[i]=v;else unwind=true;}
void runtime_vfp_load_store(std::uint32_t w)noexcept{const bool p=w&(1u<<24),u=w&(1u<<23),wb=w&(1u<<21),load=w&(1u<<20),dbl=w&(1u<<8);const unsigned rn=(w>>16)&15u,vd=(w>>12)&15u,imm=w&255u;unsigned first=dbl?((((w>>22)&1u)*16u+vd)*2u):(vd*2u+((w>>22)&1u));unsigned words=(p&&!wb)?(dbl?2u:1u):imm;if(!words||first+words>vfp_words.size()){unwind=true;return;}std::uint32_t base=g_cpu.R[rn],bytes=words*4u,address;if(p&&!wb)address=u?base+imm*4u:base-imm*4u;else if(u)address=base+(p?4u:0u);else address=base-bytes+(p?0u:4u);for(unsigned n=0;n<words;++n){if(load)vfp_words[first+n]=bus_read_u32(address+n*4u);else bus_write_u32(address+n*4u,vfp_words[first+n]);}if(wb)g_cpu.R[rn]=u?base+bytes:base-bytes;}
std::uint32_t runtime_pkhbt(std::uint32_t n,std::uint32_t m,unsigned shift)noexcept{return (n&0xffffu)|((m<<shift)&0xffff0000u);}std::uint32_t runtime_usat(std::uint32_t v,unsigned sat,unsigned shift,bool asr)noexcept{const auto signed_v=std::int32_t(v);const std::int64_t shifted=asr?std::int64_t(shift?signed_v>>shift:(signed_v<0?-1:0)):std::int64_t(std::int32_t(v<<shift));const std::uint64_t limit=sat==32?0xffffffffull:((std::uint64_t(1)<<sat)-1);if(shifted<0){g_cpu.cpsr|=CPSR_Q_BIT;return 0;}if(std::uint64_t(shifted)>limit){g_cpu.cpsr|=CPSR_Q_BIT;return std::uint32_t(limit);}return std::uint32_t(shifted);}std::uint32_t runtime_uxtah(std::uint32_t n,std::uint32_t m,unsigned rotate)noexcept{return n+runtime_uxth(m,rotate);}std::uint32_t runtime_sxtah(std::uint32_t n,std::uint32_t m,unsigned rotate)noexcept{return n+runtime_sxth(m,rotate);}std::uint32_t runtime_clz(std::uint32_t v)noexcept{return std::countl_zero(v);}std::uint32_t runtime_rev(std::uint32_t v)noexcept{return std::byteswap(v);}static std::uint32_t ror(std::uint32_t v,unsigned n)noexcept{return std::rotr(v,int(n));}std::uint32_t runtime_uxtb(std::uint32_t v,unsigned n)noexcept{return ror(v,n)&0xffu;}std::uint32_t runtime_uxth(std::uint32_t v,unsigned n)noexcept{return ror(v,n)&0xffffu;}std::uint32_t runtime_sxtb(std::uint32_t v,unsigned n)noexcept{return std::uint32_t(std::int32_t(std::int8_t(runtime_uxtb(v,n))));}std::uint32_t runtime_sxth(std::uint32_t v,unsigned n)noexcept{return std::uint32_t(std::int32_t(std::int16_t(runtime_uxth(v,n))));}std::uint32_t runtime_rev16(std::uint32_t v)noexcept{return ((v&0xff00ff00u)>>8)|((v&0x00ff00ffu)<<8);}std::uint32_t runtime_revsh(std::uint32_t v)noexcept{return std::uint32_t(std::int32_t(std::int16_t(std::uint16_t((v>>8)|((v&255)<<8)))));}
std::uint32_t runtime_ldrex(std::uint32_t a)noexcept{exclusive=a;return bus_read_u32(a);}std::uint32_t runtime_strex(std::uint32_t a,std::uint32_t v)noexcept{if(exclusive!=a)return 1;write(a,v);exclusive=~0u;return 0;}std::uint32_t runtime_ldrexh(std::uint32_t a)noexcept{exclusive=a;return bus_read_u16(a);}std::uint32_t runtime_strexh(std::uint32_t a,std::uint32_t v)noexcept{if(exclusive!=a)return 1;write(a,std::uint16_t(v));exclusive=~0u;return 0;}void runtime_cps(bool en,std::uint32_t mask)noexcept{if(mask&0x80)g_cpu.cpsr=en?(g_cpu.cpsr&~CPSR_I_BIT):(g_cpu.cpsr|CPSR_I_BIT);if(mask&0x40)g_cpu.cpsr=en?(g_cpu.cpsr&~CPSR_F_BIT):(g_cpu.cpsr|CPSR_F_BIT);}void runtime_setend(bool b)noexcept{g_cpu.cpsr=b?(g_cpu.cpsr|CPSR_E_BIT):(g_cpu.cpsr&~CPSR_E_BIT);}
std::uint32_t runtime_uxtab(std::uint32_t n,std::uint32_t m,unsigned rotate)noexcept{return n+runtime_uxtb(m,rotate);}void runtime_ldrexd(std::uint32_t a,std::uint32_t&lo,std::uint32_t&hi)noexcept{exclusive=a;lo=bus_read_u32(a);hi=bus_read_u32(a+4);}std::uint32_t runtime_strexd(std::uint32_t a,std::uint32_t lo,std::uint32_t hi)noexcept{if(exclusive!=a)return 1;write(a,lo);write(a+4,hi);exclusive=~0u;return 0;}void runtime_udf(std::uint32_t word,std::uint32_t pc)noexcept{runtime_unimplemented_op(word,pc);}
std::uint8_t bus_read_u8(std::uint32_t a)noexcept{return read<std::uint8_t>(a);}std::uint16_t bus_read_u16(std::uint32_t a)noexcept{return read<std::uint16_t>(a);}std::uint32_t bus_read_u32(std::uint32_t a)noexcept{return read<std::uint32_t>(a);}void bus_write_u8(std::uint32_t a,std::uint8_t v)noexcept{write(a,v);}void bus_write_u16(std::uint32_t a,std::uint16_t v)noexcept{write(a,v);}void bus_write_u32(std::uint32_t a,std::uint32_t v)noexcept{write(a,v);}
std::uint32_t runtime_read_user_reg(unsigned reg)noexcept{return reg<16?g_cpu.R[reg]:0;}void runtime_write_user_reg(unsigned reg,std::uint32_t value)noexcept{if(reg<16)g_cpu.R[reg]=value;}
std::uint32_t cpsr_c() noexcept{return (g_cpu.cpsr&CPSR_C_BIT)?1u:0u;}
bool arm_cond_passes_i(std::uint32_t c) noexcept{bool n=g_cpu.cpsr&CPSR_N_BIT,z=g_cpu.cpsr&CPSR_Z_BIT,carry=g_cpu.cpsr&CPSR_C_BIT,v=g_cpu.cpsr&CPSR_V_BIT;switch(c&15){case 0:return z;case 1:return !z;case 2:return carry;case 3:return !carry;case 4:return n;case 5:return !n;case 6:return v;case 7:return !v;case 8:return carry&&!z;case 9:return !carry||z;case 10:return n==v;case 11:return n!=v;case 12:return !z&&n==v;case 13:return z||n!=v;case 14:return true;default:return false;}}
static void nz(std::uint32_t r){g_cpu.cpsr=(g_cpu.cpsr&~(CPSR_N_BIT|CPSR_Z_BIT))|(r&CPSR_N_BIT)|(r?0:CPSR_Z_BIT);}
void arm_set_nzc_logic(std::uint32_t r,std::uint32_t c)noexcept{nz(r);g_cpu.cpsr=(g_cpu.cpsr&~CPSR_C_BIT)|(c?CPSR_C_BIT:0);}
void arm_set_nzcv_add(std::uint32_t a,std::uint32_t b,std::uint32_t r)noexcept{nz(r);auto w=std::uint64_t(a)+b;g_cpu.cpsr=(g_cpu.cpsr&~(CPSR_C_BIT|CPSR_V_BIT))|((w>>32)?CPSR_C_BIT:0)|(((~(a^b)&(a^r))>>31)?CPSR_V_BIT:0);}
void arm_set_nzcv_adc(std::uint32_t a,std::uint32_t b,std::uint32_t carry,std::uint32_t r)noexcept{nz(r);const auto w=std::uint64_t(a)+b+carry;g_cpu.cpsr=(g_cpu.cpsr&~(CPSR_C_BIT|CPSR_V_BIT))|((w>>32)?CPSR_C_BIT:0)|(((~(a^b)&(a^r))>>31)?CPSR_V_BIT:0);}void arm_set_nzcv_sub(std::uint32_t a,std::uint32_t b,std::uint32_t r)noexcept{nz(r);g_cpu.cpsr=(g_cpu.cpsr&~(CPSR_C_BIT|CPSR_V_BIT))|((a>=b)?CPSR_C_BIT:0)|((((a^b)&(a^r))>>31)?CPSR_V_BIT:0);}
void arm_set_nzcv_sbc(std::uint32_t a,std::uint32_t b,std::uint32_t r,std::uint32_t carry)noexcept{arm_set_nzcv_sub(a,b+(carry?0u:1u),r);}
bool runtime_slice_yield()noexcept{return false;}void runtime_trace_event(std::uint32_t,std::uint32_t,std::uint32_t,std::uint32_t,std::uint32_t)noexcept{}void runtime_msr_cpsr(std::uint32_t v,std::uint32_t mask)noexcept{std::uint32_t m=mask?mask:0xffffffffu;g_cpu.cpsr=(g_cpu.cpsr&~m)|(v&m);}