if(NOT DEFINED BUILD_DIR OR NOT DEFINED GENERATED_DIR OR NOT DEFINED OBJECT_DIR)
  message(FATAL_ERROR "BUILD_DIR, GENERATED_DIR, and OBJECT_DIR are required")
endif()
cmake_path(ABSOLUTE_PATH BUILD_DIR NORMALIZE OUTPUT_VARIABLE _build)
cmake_path(ABSOLUTE_PATH GENERATED_DIR NORMALIZE OUTPUT_VARIABLE _generated)
cmake_path(ABSOLUTE_PATH OBJECT_DIR NORMALIZE OUTPUT_VARIABLE _objects)
cmake_path(IS_PREFIX _build "${_generated}" NORMALIZE _generated_inside)
cmake_path(IS_PREFIX _build "${_objects}" NORMALIZE _objects_inside)
if(NOT _generated_inside OR NOT _objects_inside OR _generated STREQUAL _build OR _objects STREQUAL _build)
  message(FATAL_ERROR "Refusing to clean paths outside the selected build tree")
endif()
file(REMOVE_RECURSE "${_generated}" "${_objects}")
message(STATUS "Removed disposable MK7 generated sources and objects")
