if(NOT EXISTS "${INPUT}")
  message(FATAL_ERROR "ROM not found: ${INPUT}")
endif()
file(SHA512 "${INPUT}" ACTUAL)
string(TOLOWER "${ACTUAL}" ACTUAL)
string(TOLOWER "${EXPECTED}" EXPECTED_LOWER)
if(NOT ACTUAL STREQUAL EXPECTED_LOWER)
  message(FATAL_ERROR "Unsupported ROM SHA-512: ${ACTUAL}")
endif()
message(STATUS "External ROM SHA-512 verified")
